### ISSUE TITLE
problems with people plugin attaching image to avatar profile

### ISSUE THREAD

**Issue by jaimeguzman** [alexbevi/redmine_dropbox_attachments#24]
Hi @alexbevi  I using your great plugin with people plugin on my redmine 2.6 and I try to upload an image to user profile and I have this big error, I checked if the folder on tmp has permission and check if the folder on dropbox has the file, but was empty.

Also I release the cache of the redmine.

I tested on ubuntu 14.04 (bitnami image) and Redmine 2.6

```
Error log

        /opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/dropbox-api-0.4.7/lib/dropbox-api/connection/requests.rb:22:in `request'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/dropbox-api-0.4.7/lib/dropbox-api/connection/requests.rb:65:in `get'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/dropbox-api-0.4.7/lib/dropbox-api/client/raw.rb:27:in `request'
(eval):3:in `metadata'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/dropbox-api-0.4.7/lib/dropbox-api/client.rb:21:in `find'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dropbox_attachments/lib/redmine_dropbox/attachment_patch.rb:130:in `delete_from_dropbox'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:407:in `_run__1778042233974766956__destroy__2564343613921292095__callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_destroy_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:254:in `destroy'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `block in destroy'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `destroy'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_people/app/controllers/people_controller.rb:170:in `attach_avatar'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_people/app/controllers/people_controller.rb:56:in `update'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:502:in `_run__1328855463871969703__process_action__2511589333713679829__callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__3241895324289631655__call__2564343613921292095__callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:134:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/passenger-5.0.6/lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/passenger-5.0.6/lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/passenger-5.0.6/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
      

```

**Comment by alexbevi** [comment]
Hey @jaimeguzman, sorry it took so long to get back to you. I'd have to look into the redmine_people plugin to determine why this is happening, as it appears as though they're trying to delete the avatar before uploading it:

```
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_dropbox_attachments/lib/redmine_dropbox/attachment_patch.rb:130:in `delete_from_dropbox'
...
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_people/app/controllers/people_controller.rb:170:in `attach_avatar'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_people/app/controllers/people_controller.rb:56:in `update'
```

I haven't worked on this plugin in quite some time, but i'm guessing it's erroring out since the file in question doesn't exist, but you're still trying to delete it.

When I have a moment, I'll get a copy of the people plugin and try this out myself ...

**Comment by alexbevi** [comment]
This is actually a duplicate of #23 so I'll try to solve both at the same time ...

**Comment by cgomezmendez** [comment]
Any upadates?
