### ISSUE TITLE
Dropbox API v1 deprecated

### ISSUE THREAD

**Issue by VoronyukM** [alexbevi/redmine_dropbox_attachments#27]
Hello!

Today our we was surprised that this awesome plugin not work and cause an error:

```
at=info method=GET path="/attachments/download/3655/Image.166987779614.png" ... protocol=https
 Completed 500 Internal Server Error in 295.4ms
 Dropbox::API::Error::BadInput (400 - Bad input parameter - v1_retired):
   vendor/bundle/ruby/2.0.0/gems/dropbox-api-0.4.2/lib/dropbox-api/connection/requests.rb:15:in `request'
   vendor/bundle/ruby/2.0.0/gems/dropbox-api-0.4.2/lib/dropbox-api/connection/requests.rb:59:in `get'
   vendor/bundle/ruby/2.0.0/gems/dropbox-api-0.4.2/lib/dropbox-api/client/raw.rb:27:in `request'
   (eval):3:in `metadata'
   vendor/bundle/ruby/2.0.0/gems/dropbox-api-0.4.2/lib/dropbox-api/client.rb:21:in `find'
   plugins/redmine_dropbox_attachments/lib/redmine_dropbox/attachments_controller_patch.rb:27:in `redirect_to_dropbox'
   plugins/redmine_dropbox_attachments/lib/redmine_dropbox/attachments_controller_patch.rb:83:in `prepare_dropbox_redirect'
```

I suppose that the reason of  the error that the Dropbox API v1 finally turned off yesterday:

https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

> September 28, 2017: API v1 endpoints are turned off.

Are there any plans to upgrade this plugin to Dropbox API v2?

**Comment by bprotas** [comment]
@VoronyukM -

I've spiked on something very quick to use the V2 API in this plugin, because I missed the turn-off announcement and my redmine install is down so just had to get something going.  If you want to look at what I've done, you can see my fork at https://github.com/bprotas/redmine_dropbox_attachments .

**Comment by bprotas** [comment]
For those interested, I've created a PR for my attempt at V2 API support in #28 .

**Comment by VoronyukM** [comment]
@bprotas Hi Ben! Your patch works like a charm. Many thanks!!!

**Comment by yukoff** [comment]
Hi guys, sorry for being late with this deprecation - was busy with other things. @bprotas, thanks for the patch, much appreciated! I'll get back to this in a few days - I think there shouldn't be any issues, however it should be check with all supported versions of redmine. And thanks for the feedback, @VoronyukM!
