### ISSUE TITLE
Doesn't work on redmine 3.4

### ISSUE THREAD

**Issue by vinznsk** [alexbevi/redmine_dropbox_attachments#29]
I'm trying to Authorize Redmine with Dropbox. After I clicked the button in the settings:

`
Processing by UsErrorsController#error_404 as HTML
  Current user: vinznsk (id=5)
  Rendered plugins/usability/app/views/errors/error_status.html.erb (12.4ms)
Completed 404 Not Found in 103ms (Views: 11.5ms | ActiveRecord: 73.0ms)
Started GET "/settings/plugin/redmine_dropbox_attachments" for 127.0.0.1 at 2017-10-15 00:16:34 +0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_dropbox_attachments"}
  Current user: vinznsk (id=5)
  Rendered plugins/redmine_dropbox_attachments/app/views/settings/_dropbox_settings.html.erb (63.3ms)
  Rendered settings/plugin.html.erb within layouts/admin (150.2ms)
  Rendered admin/_menu.html.erb (9.4ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (167.7ms)
  Rendered plugins/custom_menu/app/views/hooks/custom_menu/_html_head.html.erb (3.7ms)
  Rendered plugins/extra_queries/app/views/extra_queries/hooks/_html_head.html.erb (1.4ms)
  Rendered plugins/global_roles/app/views/hooks/global_roles/_head.html.erb (1.4ms)
  Rendered plugins/usability/app/views/hooks/usability/_html_head.html.erb (7.5ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (1.3ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.6ms)
  Rendered plugins/custom_menu/app/views/hooks/custom_menu/_view_layouts_base_body_bottom.erb (1.2ms)
  Rendered plugins/global_roles/app/views/hooks/global_roles/_view_layouts_base_body_bottom.html.erb (0.9ms)
  Rendered plugins/redmine_zxcvbn/app/views/hooks/redmine_zxcvbn/_view_layouts_base_body_bottom.html.erb (2.4ms)
  Rendered plugins/usability/app/views/hooks/usability/_body_bottom.html.erb (1.6ms)
  Rendered layouts/base.html.erb (800.8ms)
Completed 200 OK in 1071ms (Views: 992.8ms | ActiveRecord: 18.5ms)
Started POST "/settings/plugin/redmine_dropbox_attachments" for 127.0.0.1 at 2017-10-15 00:16:40 +0300
Processing by SettingsController#plugin as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"YObFpbDAk6XuKzjthNyYy1hAc9tCI/fCWjl/gaWgEluN3bPoph/2ZJCOlN8O6e3gRSka37kScEaUd8/P+rAe2A==", "settings"=>{"DROPBOX_BASE_DIR"=>"", "DROPBOX_USE_HIERARCHY"=>"on", "DROPBOX_TOKEN"=>"", "DROPBOX_SECRET"=>""}, "commit"=>"Применить", "id"=>"redmine_dropbox_attachments"}
  Current user: vinznsk (id=5)
Redirected to http://thin_server/settings/plugin/redmine_dropbox_attachments
Completed 302 Found in 12ms (ActiveRecord: 2.2ms)
Started GET "/settings/plugin/redmine_dropbox_attachments" for 127.0.0.1 at 2017-10-15 00:16:40 +0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_dropbox_attachments"}
  Current user: vinznsk (id=5)
  Rendered plugins/redmine_dropbox_attachments/app/views/settings/_dropbox_settings.html.erb (1.4ms)
  Rendered settings/plugin.html.erb within layouts/admin (3.3ms)
  Rendered admin/_menu.html.erb (6.1ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (3.8ms)
  Rendered plugins/custom_menu/app/views/hooks/custom_menu/_html_head.html.erb (1.4ms)
  Rendered plugins/extra_queries/app/views/extra_queries/hooks/_html_head.html.erb (0.1ms)
  Rendered plugins/global_roles/app/views/hooks/global_roles/_head.html.erb (0.1ms)
  Rendered plugins/usability/app/views/hooks/usability/_html_head.html.erb (2.7ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.1ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.1ms)
  Rendered plugins/custom_menu/app/views/hooks/custom_menu/_view_layouts_base_body_bottom.erb (0.1ms)
  Rendered plugins/global_roles/app/views/hooks/global_roles/_view_layouts_base_body_bottom.html.erb (0.1ms)
  Rendered plugins/redmine_zxcvbn/app/views/hooks/redmine_zxcvbn/_view_layouts_base_body_bottom.html.erb (0.3ms)
  Rendered plugins/usability/app/views/hooks/usability/_body_bottom.html.erb (0.2ms)
  Rendered layouts/base.html.erb (78.1ms)
Completed 200 OK in 98ms (Views: 84.8ms | ActiveRecord: 6.4ms)
Started GET "/dropbox/authorize" for 127.0.0.1 at 2017-10-15 00:16:43 +0300
Processing by DropboxController#authorize as HTML
  Current user: vinznsk (id=5)
Completed 500 Internal Server Error in 452ms (ActiveRecord: 2.0ms)

OAuth::Unauthorized (400 Bad Request):
  plugins/redmine_dropbox_attachments/app/controllers/dropbox_controller.rb:12:in `authorize'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
`

**Comment by bprotas** [comment]
Hi @vinznsk , I haven't tried Redmine 3.4, but in my experience on 3.2 this plugin stopped working  on Sept 28 due to a change in Dropbox's API.  I don't think it's working on any version of Redmine right now.  I haven't tested on 3.4, but if you want feel free to give my branch that I mentioned in #28 a try and see if that resolves your issue.  Note that the authentication for v2 of Dropbox's API is slightly different; I've tried to describe the new process in the README in that PR.
