### ISSUE TITLE
Plug In Configuration Page 404s

### ISSUE THREAD

**Issue by M0d3rn15t** [alexbevi/redmine_dropbox_attachments#30]
Anyone know why the plugin configuration screen is unavailable? Loads the missing page message.

Redmine is 3.4 (Ruby is 2.3.6) installed on CentOS7 64bit with Plesk Onyx.

**Comment by M0d3rn15t** [comment]
log file entries......

```
Completed 500 Internal Server Error in 23ms (ActiveRecord: 6.1ms)

RuntimeError (translation missing: en.dropbox_plugin_not_configured):
  plugins/redmine_dropbox_attachments-master/lib/redmine_dropbox/attachment_patch.rb:39:in `dropbox_plugin_settings'
  plugins/redmine_dropbox_attachments-master/lib/redmine_dropbox/attachment_patch.rb:49:in `dropbox_client'
  plugins/redmine_dropbox_attachments-master/lib/redmine_dropbox/attachment_patch.rb:116:in `save_to_dropbox'
  plugins/redmine_people/lib/acts_as_attachable_global/lib/acts_as_attachable_global.rb:75:in `block in save_attachments'
  plugins/redmine_people/lib/acts_as_attachable_global/lib/acts_as_attachable_global.rb:71:in `each'
  plugins/redmine_people/lib/acts_as_attachable_global/lib/acts_as_attachable_global.rb:71:in `save_attachments'
  app/models/attachment.rb:285:in `attach_files'
  plugins/redmine_people/app/controllers/people_controller.rb:316:in `attach_avatar'
  plugins/redmine_people/app/controllers/people_controller.rb:119:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by M0d3rn15t** [comment]
This plugin no longer works. The one from the API v2,0 almost does.
